- name: Node directory is present
  file:
    path: /data/jenkins/slaves/cd
    state: directory
    mode: 0777
  tags: [jenkins]

- name: Job directories are present
  file:
    path: '{{ jenkins_base_dir }}/jobs/{{ item.dest }}'
    state: directory
  with_items: jenkins_jobs
  tags: [jenkins]

- name: Build jobs are present
  template:
    src: '{{ item.src }}'
    dest: '{{ jenkins_base_dir }}/jobs/{{ item.dest }}/config.xml'
    backup: yes
  with_items: jenkins_jobs
  tags: [jenkins]

- name: Container is running
  docker:
    name: jenkins
    image: jenkins:1.642.4
    ports: 8080:8080
    volumes:
      - "{{ jenkins_base_dir }}:/var/jenkins_home"
    env:
      SERVICE_ID: jenkins
  tags: [jenkins]

- name: Reload
  shell: docker restart jenkins
  tags: [jenkins, reload]
