- name: Directories are present
  file:
    dest: "{{ item }}"
    state: directory
  with_items: directories
  tags: [nginx]

- name: nginx container is running
  docker:
    image: nginx
    name: nginx
    state: running
    ports: "{{ ports }}"
    volumes: "{{ volumes }}"
  tags: [nginx]

- name: nginx config files are present
  template: src={{ item.src }} dest={{ item.dest }}
  with_items: templates
  register: result
  tags: [nginx]

- name: nginx container is restarted
  shell: docker kill -s HUP nginx
  when: result|changed
  tags: [nginx]