- name: Debian add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes
    state: present
  tags: [docker]

- name: Debian Docker is present
  apt:
    name: docker-engine
    state: latest
    force: yes
  tags: [docker]

- name: Debian python-pip is present
  apt: name=python-pip state=present
  tags: [docker]

- name: Debian docker-py is present
  pip:
    name: docker-py
    version: 1.6.0
    state: present
  tags: [docker]

- name: vagrant user is added to the docker group
  user:
    name: vagrant
    group: docker
  register: user_result
  tags: [docker]

- name: Debian Docker service is restarted
  service:
    name: docker
    state: restarted
  when: user_result|changed
  tags: [docker]
