db:
  ports:
    - 27017
  environment:
    - SERVICE_ID=books-service-db
  image: mongo
blue:
  ports:
    - 8080
  environment:
    - SERVICE_ID=books-service-blue
    - DB_PORT_27017_TCP={{ key "services/mongo/books-service-db" }}
  image: vfarcic/books-service
green:
  ports:
    - 8080
  environment:
    - SERVICE_ID=books-service-green
    - DB_PORT_27017_TCP={{ key "services/mongo/books-service-db" }}
  image: vfarcic/books-service